micronaut:
  application:
    name: orderFulfillment
  server:
    port: 8082
kafka:
  bootstrap.servers: <URL from Confluent Cloud or other Kafka broker address>
  security.protocol: SASL_SSL
  sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='<CCloud API Key>'   password='<CCloud API Secret>';"
  sasl.mechanism: PLAIN
