all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-32-238.us-west-2.compute.internal:
      ansible_host: ec2-54-245-140-18.us-west-2.compute.amazonaws.com
    ip-172-31-35-168.us-west-2.compute.internal:
      ansible_host: ec2-34-214-201-30.us-west-2.compute.amazonaws.com
    ip-172-31-36-123.us-west-2.compute.internal:
      ansible_host: ec2-54-184-69-3.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-47-219.us-west-2.compute.internal:
      ansible_host: ec2-52-10-236-180.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-10-236-180.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-10-236-180.us-west-2.compute.amazonaws.com
    ip-172-31-44-108.us-west-2.compute.internal:
      ansible_host: ec2-18-236-183-16.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-18-236-183-16.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-18-236-183-16.us-west-2.compute.amazonaws.com
    ip-172-31-38-168.us-west-2.compute.internal:
      ansible_host: ec2-35-165-223-130.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-35-165-223-130.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-35-165-223-130.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-34-201.us-west-2.compute.internal:
      ansible_host: ec2-54-186-106-238.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-45-244.us-west-2.compute.internal:
      ansible_host: ec2-52-89-231-174.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-36-116.us-west-2.compute.internal:
      ansible_host: ec2-34-212-34-18.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-40-223.us-west-2.compute.internal:
      ansible_host: ec2-34-222-123-42.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-37-61.us-west-2.compute.internal:
      ansible_host: ec2-35-162-7-227.us-west-2.compute.amazonaws.com

