all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-35-128.us-west-2.compute.internal:
      ansible_host: ec2-34-219-32-205.us-west-2.compute.amazonaws.com
    ip-172-31-34-43.us-west-2.compute.internal:
      ansible_host: ec2-34-209-193-29.us-west-2.compute.amazonaws.com
    ip-172-31-47-239.us-west-2.compute.internal:
      ansible_host: ec2-52-38-180-89.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-32-168.us-west-2.compute.internal:
      ansible_host: ec2-34-216-193-198.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-216-193-198.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-216-193-198.us-west-2.compute.amazonaws.com
    ip-172-31-46-137.us-west-2.compute.internal:
      ansible_host: ec2-34-222-153-18.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-34-222-153-18.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-34-222-153-18.us-west-2.compute.amazonaws.com
    ip-172-31-37-89.us-west-2.compute.internal:
      ansible_host: ec2-52-36-126-48.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-36-126-48.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-36-126-48.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-42-229.us-west-2.compute.internal:
      ansible_host: ec2-54-69-86-200.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-34-158.us-west-2.compute.internal:
      ansible_host: ec2-34-217-214-31.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-32-75.us-west-2.compute.internal:
      ansible_host: ec2-34-220-197-19.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-35-229.us-west-2.compute.internal:
      ansible_host: ec2-18-236-97-176.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-32-89.us-west-2.compute.internal:
      ansible_host: ec2-54-186-42-93.us-west-2.compute.amazonaws.com
