all:
  vars:
    ansible_become: true

    ssl_enabled: true

    kafka_broker_custom_listeners:
      external:
        name: EXTERNAL
        port: 9093

zookeeper:
  hosts:
    ip-172-31-37-167.us-west-2.compute.internal:
      ansible_host: ec2-34-217-144-179.us-west-2.compute.amazonaws.com
    ip-172-31-33-174.us-west-2.compute.internal:
      ansible_host: ec2-52-40-11-18.us-west-2.compute.amazonaws.com
    ip-172-31-40-166.us-west-2.compute.internal:
      ansible_host: ec2-54-149-177-218.us-west-2.compute.amazonaws.com

kafka_broker:
  hosts:
    ip-172-31-38-8.us-west-2.compute.internal:
      ansible_host: ec2-52-13-116-70.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-52-13-116-70.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-52-13-116-70.us-west-2.compute.amazonaws.com
    ip-172-31-34-189.us-west-2.compute.internal:
      ansible_host: ec2-35-163-174-182.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-35-163-174-182.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-35-163-174-182.us-west-2.compute.amazonaws.com
    ip-172-31-34-179.us-west-2.compute.internal:
      ansible_host: ec2-18-237-77-20.us-west-2.compute.amazonaws.com
      mds_advertised_listener_hostname: ec2-18-237-77-20.us-west-2.compute.amazonaws.com
      kafka_broker_custom_listeners:
        external:
          hostname: ec2-18-237-77-20.us-west-2.compute.amazonaws.com

schema_registry:
  hosts:
    ip-172-31-36-166.us-west-2.compute.internal:
      ansible_host: ec2-34-220-188-113.us-west-2.compute.amazonaws.com

kafka_rest:
  hosts:
    ip-172-31-32-144.us-west-2.compute.internal:
      ansible_host: ec2-54-218-70-55.us-west-2.compute.amazonaws.com

kafka_connect:
  hosts:
    ip-172-31-43-57.us-west-2.compute.internal:
      ansible_host: ec2-18-236-138-252.us-west-2.compute.amazonaws.com

ksql:
  hosts:
    ip-172-31-44-23.us-west-2.compute.internal:
      ansible_host: ec2-54-201-102-233.us-west-2.compute.amazonaws.com

control_center:
  hosts:
    ip-172-31-33-107.us-west-2.compute.internal:
      ansible_host: ec2-34-219-162-154.us-west-2.compute.amazonaws.com

