micronaut:
  application:
    name: orderService
kafka:
  bootstrap.servers: pkc-ep9mm.us-east-2.aws.confluent.cloud:9092
  security.protocol: SASL_SSL
  sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='OMLMDMGZDVY5ISWE'   password='q9L8K15RP3lw+oZXk3ZhmEWeHlqCovp+WNYwNvcxE6Xp6UOp+AlVX3EWqiapT+YO';"
  sasl.mechanism: PLAIN
  client.dns.lookup: use_all_dns_ips
  acks: all
